DEFAULT_SEED = 0
DEFAULT_NUM_SAMPLED_SERIES = 1
DEFAULT_BURN_IN = 1000
DEFAULT_NUM_SAMPLES = 1000
DEFAULT_NUM_CHAINS = 2
DEFAULT_NUM_JOBS = DEFAULT_NUM_CHAINS
DEFAULT_INIT_METHOD = "jitter+adapt_diag"
DEFAULT_TARGET_ACCEPT = 0.8
