import numpy as np

# Common to both models
NUM_SUBJECTS = 3
SD_MEAN_UC0 = 1
SD_SD_UC = 1
MEAN_MEAN_A0 = np.zeros((NUM_SUBJECTS, 2))
SD_SD_A = np.ones(1)
SD_SD_O = np.ones(1)
SHARE_MEAN_A0_ACROSS_SUBJECT = False
SHARE_MEAN_A0_ACROSS_DIMENSIONS = False
SHARE_SD_ACROSS_SUBJECTS = True  # same variance across subjects
SHARE_SD_ACROSS_DIMENSIONS = True  # same variance for position and speed
NUM_TIME_STEPS = 100

# Conversation model
SUBJECT_NAMES_CONVERSATION_MODEL = ["Bob", "Alice", "Dan"]
ANGULAR_FREQUENCIES_CONVERSATION_MODEL = np.array([1, 0.5, 0.1])
DAMPENING_COEFFICIENTS_CONVERSATION_MODEL = np.zeros(NUM_SUBJECTS)
DT_CONVERSATION_MODEL = 0.2
INITIAL_STATE_CONVERSATION_MODEL = np.array([[1, 0], [1, 0], [1, 0]])
SD_MEAN_A0_CONVERSATION_MODEL = np.ones((NUM_SUBJECTS, 2)) * max(
    INITIAL_STATE_CONVERSATION_MODEL[:, 0])
SAMPLING_TIME_SCALE_DENSITY_CONVERSATIONAL_MODEL = 1.0
ALLOW_SAMPLED_SUBJECT_REPETITION_CONVERSATIONAL_MODEL = False
FIX_SAMPLED_SUBJECT_SEQUENCE_CONVERSATIONAL_MODEL = True

# For sample generation
SD_A_CONVERSATION_MODEL = np.array([0.1])
SD_O_CONVERSATION_MODEL = np.array([0.01])
